### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by jgoux** [YoEight/eventstore#25]
Hello,
is there a working example for the library ?
So it could serve as demo purpose.

Thanks for this driver anyway ! :+1:

**Comment by YoEight** [comment]
I'm using it on internal projects so not yet. However, I'm currently rewriting my personal website to Snap framework using an EventStore backend. The code will be hosted publicly on Github so expect it to online in a couple of weeks.

In a meantime, would some example in the README be enough ? I also have a post on my website when I first released the library. The API didn't change that much.

http://corecursion.net/article/2015-01-13-Haskell_EventStore_TCP_Client

Don't mind the list of supported features. More have been added in the meantime

**Comment by YoEight** [comment]
I've just pushed the new code of my blog that uses an EventStore backend. I switched to Yesod framework. Unfortunately, the code isn't easy to dig out (mainly because of Yesod infrastructure code).

EventStore related stuff are located both in [Model](https://github.com/YoEight/corecursion-net/blob/master/Model.hs) and [Repository](https://github.com/YoEight/corecursion-net/blob/master/Repository.hs) modules. Hope it will help
