### ISSUE TITLE
waitTillClosed: thread blocked indefinitely in an STM transaction

### ISSUE THREAD

**Issue by Akii** [YoEight/eventstore#60]
Hey, not sure if this is a bug or I'm doing it wrong.

```
main = do
  es <- connect defaultSettings (Static "localhost" 1113)
  shutdown es
  waitTillClosed es
```

This will result in `*** Exception: thread blocked indefinitely in an STM transaction` if the connect fails (for instance if the server is not up).

I kinda feel like this should not fail since the connection is technically shut down.
From what I can see there is also no way of checking (or waiting) until the connection has been successful.

**Comment by YoEight** [comment]
Hi Akii,

`shutdown` is asynchronous, so calling `shutdown` doesn't mean everything has closed. 
`waitTillClosed` is there to assure everything has been handled properly after a `shutdown` (like handling all messages sent by the server but not carried out yet).

Now your issue, it's not bug and let me explain why. When you call `connect`, nothing happens. The client will *really* connect after a command being issued.

Calling `shutdown` is basically a no-op at this stage but still does what it has to do. Everything happens in `waitTillClosed` and here's the code:

```haskell
closed <- connIsClosed conn
unless closed retrySTM
readTMVar disposed
```
 
In this case, `connIsClosed` will always return `False`, so we hit `retrySTM`. Because `shutdown` has been called earlier, nothing will change the internal `TVar` of the connection. That's why GHC runtime issues that error, because we wait for something that will never happen.

I argue this issue isn't a bug, it's more a misuse as a GetEventStore doesn't behave like a regular SQL connection in this regard. Tell me what you think. If you agree, I will close that issue.

**Comment by Akii** [comment]
I see, after actually using the connection it becomes a bit more predictable. Thanks!
